Add stricter git hooks with prettier

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Fail on first line that fails.
+set -e
+
 # Check if this is the initial commit
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
@@ -13,31 +16,72 @@ if ! git diff-index --check --cached $against
 then
     echo "Aborting commit due to whitespace errors."
     exit 1
-else
-    # Fail on first line that fails.
-    set -e
+fi
 
-    NEW_FILES=$(git --no-pager diff --name-only --cached --diff-filter=d)
-    JS_FILES=$(echo "$NEW_FILES" | { grep .js$ || true; })
-    SNAPSHOT_FILES=$(echo "$NEW_FILES" | { grep .snap$ || true; })
-    SASS_FILES=$(echo "$NEW_FILES" | { grep .sass$ || true; })
+# Only keep staged files that are added (A), copied (C) or modified (M).
+STAGED=$(git --no-pager diff --name-only --cached --diff-filter=ACM)
+# Files which are only partly staged (eg. git add --patch).
+PATCH_STAGED=$(git --no-pager diff --name-only --diff-filter=ACM $STAGED)
+# Files which are fully staged.
+FULLY_STAGED=$(comm -23 <(echo "$STAGED") <(echo "$PATCH_STAGED"))
 
-    if [ -n "$JS_FILES" ];
+JS_STAGED=$(grep .js$ <<< "$STAGED" || true)
+JS_FULLY_STAGED=$(grep .js$ <<< "$FULLY_STAGED" || true)
+SCSS_STAGED=$(grep .scss$ <<< "$STAGED" || true)
+SCSS_FULLY_STAGED=$(grep .scss$ <<< "$FULLY_STAGED" || true)
+JSON_STAGED=$(grep .json$ <<< "$STAGED" || true)
+JSON_FULLY_STAGED=$(grep .json$ <<< "$FULLY_STAGED" || true)
+SNAPSHOT_STAGED=$(grep .snap$ <<< "$STAGED" || true)
+
+# Uncomment for debugging help.
+# tr ' ' '\n' <<< "STAGED $STAGED PATCH_STAGED $PATCH_STAGED FULLY_STAGED $FULLY_STAGED JS_STAGED $JS_STAGED JS_FULLY_STAGED $JS_FULLY_STAGED SNAPSHOT_STAGED $SNAPSHOT_STAGED"
+
+if [ -n "$JS_STAGED" ];
+then
+    # Format all files.
+    npm run formatter:js -s -- --write $JS_STAGED
+
+    # Only re-stage fully staged files.
+    if [ -n "$JS_FULLY_STAGED" ];
     then
-        npm run linter:js -s -- $JS_FILES
+        git add $JS_FULLY_STAGED
     fi
 
-    if [ -n "$SCSS_FILES" ];
+    # Lint all files.
+    npm run linter:js -s -- $JS_STAGED
+fi
+
+if [ -n "$SCSS_STAGED" ];
+then
+    # Format all files.
+    npm run formatter:js -s -- --write $SCSS_STAGED
+
+    # Only re-stage fully staged files.
+    if [ -n "$SCSS_FULLY_STAGED" ];
     then
-        npm run linter:sass -s -- $SCSS_FILES
+        git add $SCSS_FULLY_STAGED
     fi
 
-    # To test if there are changes to Sass files as well (not useful at the moment):
-    # || [ -n "$SASS_FILES" ];
-    if [ -n "$JS_FILES" ] || [ -n "$SNAPSHOT_FILES" ];
+    # Lint all files.
+    npm run linter:css -s -- $SCSS_STAGED
+fi
+
+if [ -n "$JSON_STAGED" ];
+then
+    # Format all files.
+    npm run formatter:js -s -- --write $JSON_STAGED
+
+    # Only re-stage fully staged files.
+    if [ -n "$JSON_FULLY_STAGED" ];
     then
-        npm run test:coverage -s
+        git add $JSON_FULLY_STAGED
     fi
 
-    exit 0
+    # Lint all files.
+    npm run linter:css -s -- $JSON_STAGED
+fi
+
+if [ -n "$JS_STAGED" ] || [ -n "$SNAPSHOT_STAGED" ];
+then
+    npm run test:coverage -s
 fi
